server:
    port: 8080

spring:
    jackson:
        deserialization:
          accept-empty-string-as-null-object: true
    datasource:
        url: jdbc:mysql://localhost:3306/greenhouse_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    application:
        name: greenhouse
mqtt:
    broker-url: tcp://localhost:1883
    client-id: greenhouse-app
    topic-prefix: greenhouse/

jwt:
    auth:
        app: "SmartGreenhouse"
        secret_key: ${JWT_SECRET}
        expiration: 900
    refresh:
        expiration: 604800000