server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/greenhouse_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    application:
        name: greenhouse
mqtt:
    broker-url: tcp://localhost:1883
    client-id: greenhouse-app
    topic-prefix: greenhouse/