server:
    port: 8080

spring:
    jackson:
        deserialization:
          accept-empty-string-as-null-object: true
    datasource:
        url: jdbc:mysql://localhost:3306/greenhouse_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    application:
        name: greenhouse
    mail:
        host: smtp.gmail.com
        port: 587
        username: smartgreenhouse.app@gmail.com
        password: ${EMAIL_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
                  connectiontimeout: 5000
                  timeout: 5000
                  writetimeout: 5000
app:
    email:
        from: smartgreenhouse.app@gmail.com
        verification:
            subject: "Verify Your Smart Greenhouse Account"
            expiration-hours: 24
            max-attempts-per-hour: 3
        password-reset:
            subject: "Reset Your Greenhouse Password"
            expiration-hours: 1
            max-attempts-per-hour: 3
mqtt:
    broker-url: tcp://localhost:1883
    client-id: greenhouse-app
    topic-prefix: greenhouse/

jwt:
    auth:
        app: "SmartGreenhouse"
        secret_key: ${JWT_SECRET}
        expiration: 90000000
    refresh:
        expiration: 604800000
